id: gitlab_ci_detect
info:
  name: Gitlab Ci Detect
  author: osrafi
  severity: high
  description: LibreNMS login panel was detected.
  tags: gitlab,panel
requests:
  - method: GET
    path:
      - "{{BaseURL}}/.gitlab-ci.yml"
      - "{{BaseURL}}/admin/.gitlab-ci.yml"
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - Variables
          - MYSQL
          - MYSQL_USER
          - MYSQL_PASSWORD
        condition: or
      - type: status
        status:
          - 200

